variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  NPM_CONFIG_USERCONFIG: '${ADOBE_NPMRC_V7}'

default:
  image: "docker-wf-dev.dr-uw2.adobeitc.com/core-platform/gitlab-runner-node16:latest"
  before_script:
    - git config --global user.name $JARVIS_NAME
    - git config --global user.email $JARVIS_EMAIL
    - npm ci
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .cache
    policy: pull


stages:
  - build
  - test
  - review
  - analyze
  - publish

warm_cache:
  stage: .pre
  interruptible: true
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .cache
    policy: pull-push
  script:
    - echo "Warmed cache for further jobs. Yay!"

.build-job-template: &build_job_definition
  stage: build
  interruptible: true

build:
  <<: *build_job_definition
  script:
    - npm run build
  artifacts:
    paths:
      - packages/core/dist/
      - packages/cells/dist/
      - packages/source/dist/

build-storybook:
  stage: build
  script:
    - npm run build-storybook
  artifacts:
    paths:
    - public

pages:
  script:
    - 'echo "Deploying storybook to GitLab pages..."'
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  dependencies:
    - build-storybook

.test-job-template: &test_job_definition
  needs: ['warm_cache']
  stage: test
  interruptible: true

lint:
  <<: *test_job_definition
  script:
    - npm run lint

test:
  <<: *test_job_definition
  script:
    - npm run test --ci --no-interactive


test-18:
  <<: *test_job_definition
  script:
    - npm run test-18 --ci --no-interactive

test-e2e:
  <<: *test_job_definition
  image: 'mcr.microsoft.com/playwright:v1.35.1-focal'
  script:
    - npm run test:e2e
  artifacts:
    paths:
      - test-results
      - playwright-report
    expire_in: 2 day

publish:
  stage: publish
  dependencies:
    - build
  interruptible: false
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_MERGE_REQUEST_IID == null'
      when: on_success
    - when: never
  script:
    - git remote set-url origin git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}
    - git checkout -B ${CI_BUILD_REF_NAME}
    - npm install standard-version -g
    - 'standard-version --bumpFiles package.json package-lock.json ./packages/*/package.json --no-verify --releaseCommitMessageFormat "chore: {{currentTag}}"'
    - npm publish --workspaces
    - git push --follow-tags origin ${CI_BUILD_REF_NAME} -o ci.skip

include:
  - project: 'devtools/reusable-jobs'
    ref: main
    file: '/templates/jobs/commitlint.yml'

commitlint:
  stage: .pre
  extends: .commitlint
  before_script:
    - ''

